"""The read-verb posture label, measured on ALL FOUR adapters (ADR-018).

`baron rules list` prints `instructed` for `read_code` and `read_collab`. Until
now one adapter (pydantic-ai) was measured and the label spoke for four. These
tests supply the missing three.

Each is the same experiment: hand baron a persona that DENIES the read verbs,
let it generate that adapter's runtime kit, and inspect **what baron generated**
for any construct a runtime would read as a tool allow/deny list. The control is
a second persona identical but for the two read verbs — if the emitted
machine-readable surface is byte-identical across the pair, nothing baron emits
is even a *function* of the denial, and the denial reaches prose only. That is
what `instructed` means.

The honest bound, restated because it is easy to lose: a negative verdict says
**baron emits no mechanism**, not that the runtime cannot enforce the verb. Both
the `claude` and `code-puppy` HYDRATE.md recipes describe a Tier-3 path
(`.claude/agents/<slug>.md`, a code-puppy agent JSON) whose `tools:` allow-list
*does* omit read tools — hand-authored in-session by whoever follows the recipe,
never generated by `baron init`. An instruction that a human may or may not
follow is the definition of `instructed`, and `baron rules list` speaks for what
baron ships.
"""

from __future__ import annotations

from pathlib import Path

import pytest

import omission
from omission import (  # the reusable harness; see its module docstring
    READ_VERBS,
    assert_emits_no_omission_mechanism,
    emit_kit,
    probe,
    scaffold_repo,
)

DENY_SLUG = "blinkered"
ALLOW_SLUG = "wideeyed"


def persona(slug: str, *, reads: bool) -> str:
    """The A/B pair: identical specs differing ONLY in the two read verbs."""
    allow = ["read_code", "read_collab"] if reads else []
    allow.append("write_code")
    deny = [] if reads else ["read_code", "read_collab"]
    deny += ["open_pr", "run_tests", "merge_pr", "push_main", "force_push",
             "edit_other_personas"]
    lines = [
        f"persona: {slug.title()}",
        f"slug: {slug}",
        "archetype: dev",
        "identity:",
        f"  git_name: {slug.title()}",
        f"  git_email: {slug}@example.invalid",
        f'  commit_prefix: "{slug}:"',
        f"  routing_label: agent-{slug}",
        "capabilities:",
        "  allow:",
        *[f"    - {v}" for v in allow],
        "  deny:",
        *[f"    - {v}" for v in deny],
    ]
    return "\n".join(lines) + "\n"


def test_the_four_adapters_are_measured_on_the_same_input() -> None:
    """The denying persona here IS the one the pydantic-ai gate measures.

    Four adapters, one input. If the gate's fixture is ever edited, this fails
    and the three static tests below stop claiming to measure the same thing.
    """
    from test_pydantic_ai import DENIES_READS_PERSONA

    assert persona(DENY_SLUG, reads=False) == DENIES_READS_PERSONA


def _pair(tmp_path: Path, adapter: str):
    repo = scaffold_repo(tmp_path / adapter, adapter)
    denied = emit_kit(repo, DENY_SLUG, persona(DENY_SLUG, reads=False))
    allowed = emit_kit(repo, ALLOW_SLUG, persona(ALLOW_SLUG, reads=True))
    return repo, denied, allowed


def _assert_denial_lands_in_prose_only(denied, allowed) -> None:
    """The denial reaches the persona's prose and nothing machine-readable."""
    body = "\n".join(a.text for a in denied.of_kind(omission.KIND_PROSE))
    assert "Never read the code repo." in body
    assert "Never read the collab repo." in body
    permissive = "\n".join(a.text for a in allowed.of_kind(omission.KIND_PROSE))
    assert "Never read the code repo." not in permissive

    # ...and every machine-readable artifact is byte-identical across the pair,
    # so no emitted config is a function of the read verbs at all.
    assert denied.paths == allowed.paths
    for artifact in denied.of_kind(omission.KIND_CONFIG):
        assert denied.normalized(artifact.path) == allowed.normalized(artifact.path), (
            f"{denied.adapter}: {artifact.path} changed when the read verbs were "
            "denied — that is a mechanism, re-measure the label"
        )


def test_claude_kit_emits_no_read_tool_omission_mechanism(tmp_path: Path) -> None:
    """MEASURED (adapter 2 of 4): the `claude` kit cannot omit read tools.

    `baron init --runtime claude` emits exactly one machine-readable artifact,
    `.claude/settings.json`, and wires only hooks into it: no `permissions`
    block, no `allowedTools`/`disallowedTools`, and no `.claude/agents/<slug>.md`
    subagent (the Tier-3 construct its own HYDRATE.md documents) anywhere.
    """
    repo, denied, allowed = _pair(tmp_path, "claude")

    for verb in READ_VERBS:
        verdict = probe(denied, verb)
        assert_emits_no_omission_mechanism(verdict)
        assert verdict.inspected == (".claude/settings.json",)

    # The closed key allowlist: hook wiring and nothing else, at any depth.
    keys = omission.settings_keys(denied)
    assert keys <= omission.CLAUDE_SETTINGS_KEYS, sorted(keys - omission.CLAUDE_SETTINGS_KEYS)
    assert not keys & omission.CLAUDE_TOOL_GATING_KEYS

    # Nothing gates tools from OUTSIDE the kit either: baron writes no
    # repo-level .claude/ (a settings.json there would reach every session).
    root = repo.root
    assert not (root / ".claude").exists()
    assert sorted(p.relative_to(root).as_posix() for p in root.rglob(".claude")) == sorted(
        f"agents/{slug}/runtime/.claude"
        for slug in (DENY_SLUG, ALLOW_SLUG, "carson", "iris")
    )

    _assert_denial_lands_in_prose_only(denied, allowed)


def test_code_puppy_kit_emits_no_read_tool_omission_mechanism(tmp_path: Path) -> None:
    """MEASURED (adapter 3 of 4): the `code-puppy` kit is prose only.

    code-puppy's real enforcement surface is the agent JSON's `tools` list
    (`JSONAgent.get_available_tools()` filters against `TOOL_REGISTRY`). `baron
    init` emits no JSON at all for this runtime — only the Tier-1 `AGENTS.md`
    fallback its HYDRATE.md documents. The JSON agent is hand-authored
    in-session; nothing baron generates can omit `read_file`/`list_files`/`grep`.
    """
    _repo, denied, allowed = _pair(tmp_path, "code-puppy")

    for verb in READ_VERBS:
        verdict = probe(denied, verb)
        assert_emits_no_omission_mechanism(verdict)
        assert verdict.prose_only, verdict.inspected
    assert not [p for p in denied.paths if p.endswith(".json")]

    _assert_denial_lands_in_prose_only(denied, allowed)


def test_generic_kit_emits_no_read_tool_omission_mechanism(tmp_path: Path) -> None:
    """MEASURED (adapter 4 of 4): the `generic` kit is prose only, by design.

    Tier 1 has no allow-list surface to emit into — its HYDRATE.md says so in
    as many words ("It emits no ENFORCED artifact"). This test holds baron to it.
    """
    _repo, denied, allowed = _pair(tmp_path, "generic")

    for verb in READ_VERBS:
        verdict = probe(denied, verb)
        assert_emits_no_omission_mechanism(verdict)
        assert verdict.prose_only, verdict.inspected
    assert "generic" in omission.NO_KNOWN_MECHANISM
    assert omission.READ_TOOLS["generic"] == ()

    _assert_denial_lands_in_prose_only(denied, allowed)


def test_static_inspection_refuses_to_clear_the_executable_adapter(tmp_path: Path) -> None:
    """pydantic-ai is NOT cleared statically — the harness says so and names the gate.

    Its kit is executable Python; what it registers is a property of running it.
    A harness that quietly returned "no mechanism" here would be manufacturing
    the fourth measurement instead of making it.
    """
    repo = scaffold_repo(tmp_path / "pai", "pydantic-ai")
    denied = emit_kit(repo, DENY_SLUG, persona(DENY_SLUG, reads=False))
    verdict = probe(denied, "read_code")

    assert verdict.needs_live_measurement
    assert "test_denying_read_code_does_not_omit_read_tools" in verdict.needs_live_measurement[0]
    with pytest.raises(AssertionError, match="static inspection may not clear"):
        assert_emits_no_omission_mechanism(verdict)


def test_the_harness_detects_a_mechanism_when_one_is_present(tmp_path: Path) -> None:
    """Negative control: the three tests above are only worth their assertions
    if the harness can FAIL. Plant each known mechanism and watch it fire."""
    import json

    repo = scaffold_repo(tmp_path / "claude", "claude")
    kit = repo.root / "agents" / "carson" / "runtime"

    # 1. a hand-written permissions.deny in the emitted settings file
    settings = kit / ".claude" / "settings.json"
    doc = json.loads(settings.read_text(encoding="utf-8"))
    doc["permissions"] = {"deny": ["Read", "Grep", "Glob"]}
    settings.write_text(json.dumps(doc, indent=2), encoding="utf-8")
    verdict = probe(omission.read_kit(repo, "carson"), "read_code")
    assert any(m.startswith("claude.settings.tool-gating") for m in verdict.mechanisms), verdict
    with pytest.raises(AssertionError, match="DOES emit a mechanism"):
        assert_emits_no_omission_mechanism(verdict)

    # 2. a Tier-3 subagent with a minimal tools allow-list
    settings.write_text(json.dumps({"hooks": {}}, indent=2), encoding="utf-8")
    subagent = kit / ".claude" / "agents" / "carson.md"
    subagent.parent.mkdir(parents=True, exist_ok=True)
    subagent.write_text("---\nname: carson\ntools: Bash, Write\n---\n", encoding="utf-8")
    verdict = probe(omission.read_kit(repo, "carson"), "read_code")
    assert any(m.startswith("claude.subagent.tools") for m in verdict.mechanisms), verdict
    # An unclassified artifact is a failure in its own right, before any mechanism.
    assert ".claude/agents/carson.md" in verdict.unclassified
    with pytest.raises(AssertionError, match="never classified"):
        assert_emits_no_omission_mechanism(verdict)

    # 3. a code-puppy agent JSON in a kit that should have none
    cp_repo = scaffold_repo(tmp_path / "cp", "code-puppy")
    (cp_repo.root / "agents" / "carson" / "runtime" / "carson.json").write_text(
        json.dumps({"name": "carson", "tools": ["read_file"]}), encoding="utf-8"
    )
    verdict = probe(omission.read_kit(cp_repo, "carson"), "read_code")
    assert any(m.startswith("code-puppy.agent-json.tools") for m in verdict.mechanisms), verdict


def test_the_label_rests_on_one_measurement_per_shipped_adapter() -> None:
    """Every adapter baron ships is named, with the measurement behind it.

    This is the anti-drift lock the round-3 wording could not provide: add a
    fifth adapter and the label's basis fails until someone measures it.
    """
    from baron import rules, scaffold

    assert set(rules.READ_VERB_MEASUREMENTS) == set(scaffold.ADAPTERS)
    assert set(rules.READ_VERB_MEASUREMENTS) == set(omission.KIT_ARTIFACTS)
    # ...and every one of them is something the harness actually looks at, so a
    # clean verdict can never mean "nobody looked".
    for adapter in scaffold.ADAPTERS:
        assert omission._accounted_for(adapter), adapter
    for adapter, measurement in rules.READ_VERB_MEASUREMENTS.items():
        assert measurement.strip(), adapter
        assert "test_" in measurement, adapter

    loaded = rules.load_rules()
    for verb in READ_VERBS:
        assert loaded.enforcement(verb) == rules.ENFORCEMENT_ADAPTER_DEPENDENT
        assert loaded.label(verb) == "instructed"
        assert loaded.caveat(verb) == rules.LABEL_CAVEAT
    # The caveat states the bound, not just the result.
    assert "baron emits no mechanism" in rules.LABEL_CAVEAT
    for adapter in scaffold.ADAPTERS:
        assert adapter in rules.LABEL_CAVEAT
