#!/usr/bin/env python3
"""Render the published doc pages from their markdown sources. Stdlib only.

    python3 dashboard/build_docs.py           # write the pages
    python3 dashboard/build_docs.py --check   # fail if the pages are stale (CI)

`docs/product-overview.md` and `docs/capability-value-map.md` stay the single
source of truth. The pages under `dashboard/overview/` and `dashboard/value-map/`
are a *styled projection* of them — committed (GitHub Pages publishes the tree as
it stands, exactly like `dashboard/data/fleet.json`) and regenerated by this
script. Nothing here rewrites prose: if a sentence is wrong on the page, it is
wrong in the markdown.

`--check` is the drift guard. It re-renders into memory and diffs against the
committed HTML, so a docs edit that never reached the site fails CI instead of
quietly publishing last week's copy.

The markdown subset is deliberately the one these two documents use: ATX
headings, paragraphs, `-`/`1.` lists with lazy continuation, pipe tables, `---`
rules, and inline code / links / bold / italic. It is not a general markdown
implementation and does not try to be — an unsupported construct should be
noticed as a rendering bug, not silently half-handled.
"""

from __future__ import annotations

import argparse
import html
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DASHBOARD = ROOT / "dashboard"
REPO_URL = "https://github.com/vggg/barony"
BLOB = f"{REPO_URL}/blob/main"

STATUS_WORDS = ("proven", "instrumented", "aspirational")


# --------------------------------------------------------------------- blocks

def parse_blocks(md: str) -> list[dict]:
    """Markdown text -> a flat list of block dicts."""
    lines = md.splitlines()
    blocks: list[dict] = []
    i = 0
    n = len(lines)

    item_re = re.compile(r"^(\s*)(?:-\s+|(\d+)\.\s+)(.*)$")

    while i < n:
        line = lines[i]
        stripped = line.strip()

        if not stripped:
            i += 1
            continue

        if stripped.startswith("#"):
            m = re.match(r"^(#+)\s+(.*)$", stripped)
            blocks.append({"t": "h", "level": len(m.group(1)), "text": m.group(2).strip()})
            i += 1
            continue

        if re.fullmatch(r"-{3,}", stripped):
            blocks.append({"t": "hr"})
            i += 1
            continue

        # pipe table: a header row followed by a delimiter row
        if stripped.startswith("|") and i + 1 < n and re.fullmatch(
            r"\|[\s:|-]+\|", lines[i + 1].strip()
        ):
            head = split_row(lines[i])
            i += 2
            rows = []
            while i < n and lines[i].strip().startswith("|"):
                rows.append(split_row(lines[i]))
                i += 1
            blocks.append({"t": "table", "head": head, "rows": rows})
            continue

        m = item_re.match(line)
        if m:
            kind = "ol" if m.group(2) else "ul"
            items: list[str] = []
            while i < n and lines[i].strip():
                mi = item_re.match(lines[i])
                if mi:
                    items.append(mi.group(3).strip())
                elif items:  # lazy continuation of the previous item
                    items[-1] += " " + lines[i].strip()
                else:
                    break
                i += 1
            blocks.append({"t": kind, "items": items})
            continue

        # paragraph: soft-wrapped until a blank line or a block starter
        para = []
        while i < n and lines[i].strip():
            s = lines[i].strip()
            if s.startswith("#") or s.startswith("|") or re.fullmatch(r"-{3,}", s) or item_re.match(lines[i]):
                break
            para.append(s)
            i += 1
        if para:
            blocks.append({"t": "p", "text": " ".join(para)})
        else:
            i += 1

    return blocks


def split_row(line: str) -> list[str]:
    """Split a pipe-table row, honouring `\\|` — a literal pipe inside a cell.

    `baron identity register\\|enroll\\|protect` is one cell, not four. Splitting
    naively silently grows the row past its colgroup, which is the kind of bug
    that renders as a faint layout wobble rather than an error.
    """
    cells = re.split(r"(?<!\\)\|", line.strip().strip("|"))
    return [c.strip().replace("\\|", "|") for c in cells]


# --------------------------------------------------------------------- inline

INLINE_RE = re.compile(
    r"`(?P<code>[^`]+)`"
    r"|\[(?P<ltext>[^\]]+)\]\((?P<lhref>[^)]+)\)"
    r"|\*\*(?P<bold>.+?)\*\*"
    r"|\*(?P<em>[^*]+)\*"
)


def inline(md: str) -> str:
    """Render inline markdown. Escapes everything that is not a token."""
    out = []
    pos = 0
    for m in INLINE_RE.finditer(md):
        out.append(html.escape(md[pos:m.start()]))
        if m.group("code") is not None:
            out.append(f"<code>{html.escape(m.group('code'))}</code>")
        elif m.group("ltext") is not None:
            out.append(f'<a href="{html.escape(href(m.group("lhref")))}">{inline(m.group("ltext"))}</a>')
        elif m.group("bold") is not None:
            out.append(f"<strong>{inline(m.group('bold'))}</strong>")
        else:
            out.append(f"<em>{inline(m.group('em'))}</em>")
        pos = m.end()
    out.append(html.escape(md[pos:]))
    return "".join(out)


def href(target: str) -> str:
    """Rewrite links that were written relative to docs/.

    The two rendered pages link to each other on the site; everything else in
    `docs/` has no page of its own and resolves to the file on GitHub, which is
    a real destination rather than a 404 the reader discovers.
    """
    if target.startswith(("http://", "https://", "#", "mailto:")):
        return target
    if target == "product-overview.md":
        return "../overview/"
    if target == "capability-value-map.md":
        return "../value-map/"
    if target.startswith("adr/") and target.endswith("/"):
        return f"{REPO_URL}/tree/main/docs/{target.rstrip('/')}"
    return f"{BLOB}/docs/{target}"


def plain(md: str) -> str:
    """Strip inline markup — for titles, slugs and `data-label` attributes."""
    s = re.sub(r"\[([^\]]+)\]\([^)]+\)", r"\1", md)
    s = re.sub(r"[`*]", "", s)
    return s.strip()


def slug(text: str) -> str:
    s = plain(text).lower()
    s = re.sub(r"[^a-z0-9]+", "-", s)
    return s.strip("-")


# ---------------------------------------------------------------------- pills

def status_cell(md: str) -> str:
    """Render a Status cell: the leading bold verdict becomes coloured pills.

    Cells read like `**instrumented** — the gate ships and refuses; …` or
    `**proven for the mechanism, aspirational for the rate.**`. Both keep their
    sentence; only the status words themselves are promoted to pills, so a mixed
    verdict stays legible as a mixed verdict instead of being rounded to one.
    """
    m = re.match(r"\*\*(.+?)\*\*", md)
    if not m:
        return inline(md)
    inner, rest = m.group(1), md[m.end():]

    if plain(inner).lower() in STATUS_WORDS:
        return pill(plain(inner)) + inline(rest)

    word_re = re.compile(r"\b(" + "|".join(STATUS_WORDS) + r")\b", re.IGNORECASE)
    parts, pos = [], 0
    for wm in word_re.finditer(inner):
        parts.append(inline(inner[pos:wm.start()]))
        parts.append(pill(wm.group(1)))
        pos = wm.end()
    parts.append(inline(inner[pos:]))
    body = "".join(parts)
    return (body if word_re.search(inner) else f"<strong>{body}</strong>") + inline(rest)


def pill(word: str) -> str:
    return f'<span class="pill {word.lower()}">{html.escape(word)}</span>'


# ---------------------------------------------------------------------- render

def render_table(block: dict) -> str:
    head, rows = block["head"], block["rows"]
    labels = [plain(h) for h in head]
    status_cols = {i for i, h in enumerate(labels) if h.lower() == "status"}
    wide = len(head) >= 4

    out = ['<div class="tbl-wrap">']
    out.append(f'<table class="{"map" if wide else "narrow"}">')
    if wide:
        cols = "".join(
            f'<col class="c-{"status" if i in status_cols else ("cap" if i == 0 else "prose")}">'
            for i in range(len(head))
        )
        out.append(f"<colgroup>{cols}</colgroup>")
    out.append("<thead><tr>" + "".join(f"<th>{inline(h)}</th>" for h in head) + "</tr></thead>")
    out.append("<tbody>")
    for row in rows:
        cells = []
        for i, cell in enumerate(row):
            body = status_cell(cell) if (i in status_cols or (len(head) == 2 and i == 0)) else inline(cell)
            label = html.escape(labels[i] if i < len(labels) else "")
            cells.append(f'<td data-label="{label}">{body}</td>')
        out.append("<tr>" + "".join(cells) + "</tr>")
    out.append("</tbody></table></div>")
    return "\n".join(out)


def render_body(blocks: list[dict]) -> str:
    """Render the blocks of one section."""
    out = []
    cards: list[str] = []

    def flush_cards():
        if cards:
            out.append('<div class="cards-col">\n' + "\n".join(cards) + "\n</div>")
            cards.clear()

    i = 0
    while i < len(blocks):
        b = blocks[i]
        if b["t"] == "h" and b["level"] == 3:
            # A `###` heading opens a capability card that runs to the next one.
            j = i + 1
            inner = []
            while j < len(blocks) and not (blocks[j]["t"] == "h" and blocks[j]["level"] <= 3):
                inner.append(blocks[j])
                j += 1
            card = [f'<article class="cap">', f"<h3>{inline(b['text'])}</h3>"]
            card.append(render_simple(inner))
            card.append("</article>")
            cards.append("\n".join(card))
            i = j
            continue
        flush_cards()
        out.append(render_simple([b]))
        i += 1
    flush_cards()
    return "\n".join(x for x in out if x)


def render_simple(blocks: list[dict]) -> str:
    out = []
    for b in blocks:
        if b["t"] == "p":
            text = b["text"]
            # A paragraph that is bold end to end is a thesis statement, not prose.
            if re.fullmatch(r"\*\*.+\*\*", text) and text.count("**") == 2:
                out.append(f'<div class="thesis"><p>{inline(text[2:-2])}</p></div>')
            else:
                out.append(f"<p>{inline(text)}</p>")
        elif b["t"] in ("ul", "ol"):
            items = "\n".join(f"<li>{inline(x)}</li>" for x in b["items"])
            out.append(f"<{b['t']}>\n{items}\n</{b['t']}>")
        elif b["t"] == "table":
            out.append(render_table(b))
        elif b["t"] == "hr":
            out.append("<hr>")
        elif b["t"] == "h":
            lvl = min(b["level"], 4)
            out.append(f"<h{lvl}>{inline(b['text'])}</h{lvl}>")
    return "\n".join(out)


# ------------------------------------------------------------------ page shell

def nav(active: str) -> str:
    links = [
        ("../", "Fleet dashboard", "dashboard"),
        ("../overview/", "Product overview", "overview"),
        ("../value-map/", "Capability map", "value-map"),
    ]
    items = "".join(
        f'<a href="{h}"{" class=\"on\"" if k == active else ""}>{t}</a>' for h, t, k in links
    )
    items += f'<a class="ext" href="{REPO_URL}">GitHub&nbsp;↗</a>'
    return (
        '<nav class="nav"><div class="nav-in">'
        f'<a class="nav-brand" href="../"><span class="glyph">&#9819;</span> Barony</a>'
        f'<div class="nav-links">{items}</div>'
        "</div></nav>"
    )


def page(*, title, description, active, hero, toc, sections, source) -> str:
    return f"""<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{html.escape(title)}</title>
<meta name="description" content="{html.escape(description)}">
<meta property="og:title" content="{html.escape(title)}">
<meta property="og:description" content="{html.escape(description)}">
<link rel="icon" href="data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' viewBox='0 0 100 100'><text y='.9em' font-size='90'>&#9819;</text></svg>">
<link rel="stylesheet" href="../assets/site.css">
</head>
<body>
<!-- GENERATED from {source} by dashboard/build_docs.py — do not edit by hand. -->
{nav(active)}
<div class="wrap">
{hero}
{toc}
{sections}
<footer class="foot">
  <span>Rendered from <a href="{BLOB}/{source}"><code>{source}</code></a> — the markdown is the source of truth.</span>
  <span class="src">regenerate: ./dashboard/build-docs.sh</span>
</footer>
</div>
</body>
</html>
"""


def split_sections(blocks: list[dict]) -> tuple[list[dict], list[tuple[str, str, list[dict]]]]:
    """Split into (intro blocks, [(number, title, body blocks)]) on `##`."""
    intro: list[dict] = []
    sections: list[tuple[str, str, list[dict]]] = []
    cur = None
    for b in blocks[1:]:  # blocks[0] is the h1
        if b["t"] == "h" and b["level"] == 2:
            m = re.match(r"^(\d+)\.\s+(.*)$", b["text"])
            cur = ((m.group(1), m.group(2)) if m else ("", b["text"]), [])
            sections.append((cur[0][0], cur[0][1], cur[1]))
            continue
        if cur is None:
            if b["t"] != "hr":
                intro.append(b)
        else:
            cur[1].append(b)
    return intro, sections


def hero_html(h1: str, intro: list[dict], *, callout_bold: bool) -> str:
    """Hero from the doc's own h1 and the paragraphs above the first section.

    The h1 splits on its em dash: `Barony — Product Overview` gives the eyebrow
    and the title. The first paragraph is the lede — in both documents that is
    the sentence the author wants read first.
    """
    if "—" in h1:
        eyebrow, title = (x.strip() for x in h1.split("—", 1))
    else:
        eyebrow, title = "Barony", h1
    paras = [b for b in intro if b["t"] == "p"]
    out = ['<header class="hero">']
    out.append(f'<div class="eyebrow">{inline(eyebrow)}</div>')
    out.append(f"<h1>{inline(title[:1].upper() + title[1:])}</h1>")
    if paras:
        first = paras[0]["text"]
        if re.fullmatch(r"\*\*.+\*\*", first) and first.count("**") == 2:
            first = first[2:-2]
        out.append(f'<p class="lede">{inline(first)}</p>')
    tail = []
    for p in paras[1:]:
        if callout_bold and p["text"].startswith("**"):
            tail.append(f'<div class="callout"><p>{inline(p["text"])}</p></div>')
        else:
            tail.append(f'<p class="standfirst">{inline(p["text"])}</p>')
    out.extend(tail)
    out.append("</header>")
    # Non-paragraph intro blocks (the value map's status legend) follow the hero.
    rest = [b for b in intro if b["t"] not in ("p", "hr")]
    if rest:
        out.append(render_simple(rest))
    return "\n".join(out)


def toc_html(sections) -> str:
    if len(sections) < 3:
        return ""
    items = "\n".join(
        f'<li><span class="n">{html.escape(num or "·")}</span>'
        f'<a href="#{slug(title)}">{inline(title)}</a></li>'
        for num, title, _ in sections
    )
    return f'<nav class="toc"><h2>On this page</h2><ol>{items}</ol></nav>'


def sections_html(sections) -> str:
    out = []
    for num, title, body in sections:
        num_html = f'<span class="sec-num">{html.escape(num)}</span>' if num else ""
        out.append(
            f'<section class="sec" id="{slug(title)}">'
            f'<div class="sec-head">{num_html}<h2>{inline(title)}</h2></div>'
            f"{render_body(body)}</section>"
        )
    return "\n".join(out)


def build(source_rel: str, out_rel: str, *, active, title, description, callout_bold) -> tuple[Path, str]:
    md = (ROOT / source_rel).read_text(encoding="utf-8")
    blocks = parse_blocks(md)
    h1 = blocks[0]["text"]
    intro, sections = split_sections(blocks)
    return (ROOT / out_rel), page(
        title=title,
        description=description,
        active=active,
        hero=hero_html(h1, intro, callout_bold=callout_bold),
        toc=toc_html(sections),
        sections=sections_html(sections),
        source=source_rel,
    )


PAGES = [
    dict(
        source_rel="docs/product-overview.md",
        out_rel="dashboard/overview/index.html",
        active="overview",
        title="Barony — Product Overview",
        description=(
            "Barony proves that agent-written code was reviewed by something other than the "
            "thing that wrote it — as signed artifacts in your own repo, checkable offline, "
            "on any forge."
        ),
        callout_bold=False,
    ),
    dict(
        source_rel="docs/capability-value-map.md",
        out_rel="dashboard/value-map/index.html",
        active="value-map",
        title="Barony — Capability → Value → Metric",
        description=(
            "One row per Barony capability: what it delivers, the metric that moves if it "
            "works, how that metric is obtained, and whether anyone has obtained it yet."
        ),
        callout_bold=True,
    ),
]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--check", action="store_true", help="fail if a committed page is stale")
    args = ap.parse_args()

    stale = []
    for spec in PAGES:
        path, rendered = build(**spec)
        rel = path.relative_to(ROOT)
        if args.check:
            current = path.read_text(encoding="utf-8") if path.exists() else ""
            if current != rendered:
                stale.append((rel, spec["source_rel"]))
                print(f"  STALE  {rel}  (does not match {spec['source_rel']})")
            else:
                print(f"  ok     {rel}")
        else:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered, encoding="utf-8")
            print(f"  wrote  {rel}  ({len(rendered)} bytes)")

    if args.check and stale:
        print(
            "\nFAIL: the published pages do not match their markdown sources.\n"
            "      Run ./dashboard/build-docs.sh and commit the result."
        )
        return 1
    if args.check:
        print("\nOK: published pages match their markdown sources.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
