#!/usr/bin/env bash
# {{PERSONA_NAME}} ({{PERSONA_SLUG}}) — persona sidecar for {{PROJECT_NAME}} (ADR-026).
# GENERATED by `baron init` ({{DATE}}) for the {{RUNTIME}} runtime, one per persona.
#
# A persona as a DEPLOYABLE UNIT: the emitted runtime kit
# (agents/{{PERSONA_SLUG}}/runtime/) + a work loop. The loop is `baron sidecar run`:
# sync the collab repo, sweep _handoff/ for items addressed to this persona (review
# feedback before new work, per the session ritual), invoke the runtime for ONE unit
# of work, then commit and push the outcome. baron syncs, sweeps and commits; the
# RUNTIME owns the model loop (ADR-007) — which is why the invocation below lives in
# your repo, not inside baron.
#
# Trigger: {{TRIGGER}} (agents/{{PERSONA_SLUG}}/persona.yaml → runtime.trigger).
#   interactive — run by hand; the loop is the human's session (--watch is refused).
#   event       — the wake spawns it (.github/workflows/baron-notify.yml, ADR-010).
#   cron        — a scheduler drives it (launchd/systemd/cron), or `--watch` self-paces.
#
# Usage:
#   ./sidecar.sh                  one cycle
#   ./sidecar.sh --dry-run        plan + brief only: no runtime, no commit, no push
#   ./sidecar.sh --watch          long-running (cron/event triggers only)
#   ./sidecar.sh --force          run even when the sweep finds nothing to do
#
# Schedule it (cron trigger), e.g. launchd on macOS or:
#   */15 * * * * {{PERSONA_SLUG}}-sidecar >/dev/null 2>&1   # see logs/ for output

set -uo pipefail

PERSONA="{{PERSONA_SLUG}}"
HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
COLLAB="$(cd "${HERE}/../.." && pwd)"
LOG_DIR="${BARON_SIDECAR_LOG_DIR:-${HERE}/logs}"
BARON="${BARON:-baron}"

# ┌──────────────────────────────────────────────────────────────────────────────┐
# │ PROJECT-OWNED SLOT — the runtime invocation. `baron sidecar run` never        │
# │ defaults to a model binary; this launcher, which lives in YOUR repo, does.    │
# │ The persona work brief arrives on the command's stdin (and as a file at       │
# │ $BARON_SIDECAR_BRIEF). Override per machine with $BARON_SIDECAR_CMD.          │
# └──────────────────────────────────────────────────────────────────────────────┘
RUNTIME_CMD="${BARON_SIDECAR_CMD:-{{RUNTIME_CMD}}}"

mkdir -p "$LOG_DIR"
# Cycle logs are local operational output, never coordination artifacts — keep them
# out of the substrate so `baron status` does not read a running sidecar as drift.
[[ -f "${LOG_DIR}/.gitignore" ]] || printf '*\n' >"${LOG_DIR}/.gitignore"
LOG="${LOG_DIR}/$(date +%Y-%m-%d).log"
log() { printf '[%s] %s\n' "$(date '+%Y-%m-%d %H:%M:%S')" "$*" >>"$LOG"; }

if ! command -v "$BARON" >/dev/null 2>&1; then
  echo "sidecar: \`$BARON\` is not on PATH — install it (pip install barony) or set \$BARON" >&2
  exit 127
fi
if [[ -z "${RUNTIME_CMD// /}" ]]; then
  echo "sidecar: no runtime command — fill RUNTIME_CMD in $0 (the PROJECT-OWNED SLOT)" >&2
  echo "         or export BARON_SIDECAR_CMD. Pass --dry-run to inspect the brief first." >&2
  [[ " $* " == *" --dry-run "* ]] || exit 2
fi

log "cycle start — persona=${PERSONA} collab=${COLLAB} args=$*"
"$BARON" sidecar run "$PERSONA" --collab "$COLLAB" --cmd "$RUNTIME_CMD" "$@" 2>&1 | tee -a "$LOG"
rc=${PIPESTATUS[0]}
log "cycle end — exit ${rc}"
exit "$rc"
