"""Runtime adapters: hydrate a runtime-neutral persona.yaml into a live agent.

Each adapter lives in its own module and carries its own (optional) runtime
dependencies — importing :mod:`baron.runtimes` itself needs nothing beyond
baron's core deps, so the CLI can emit bootstrap scripts without any extra
installed. First adapter: :mod:`baron.runtimes.pydantic_ai`
(``pip install 'barony[pydantic-ai]'``).
"""

from __future__ import annotations

from pathlib import Path

_PYDANTIC_AI_TEMPLATE = '''\
"""Bootstrap script for the {slug} persona on pydantic-ai — generated by
`baron hydrate pydantic-ai`; ready to edit (pick your model below).

Running this script needs the optional extra:

    pip install 'barony[pydantic-ai]'
"""

from pathlib import Path

from baron.runtimes.pydantic_ai import build_agent

PERSONA_FILE = Path({persona_file!r})
COLLAB_ROOT = Path({collab_root!r})  # the persona's working-copy root

# TODO: replace with your model, e.g. "anthropic:claude-sonnet-4-6".
# "test" (pydantic-ai's built-in TestModel) runs fully offline — good for a
# first smoke run, useless for real work.
MODEL = "test"

agent = build_agent(PERSONA_FILE, collab_root=COLLAB_ROOT, model=MODEL)

if __name__ == "__main__":
    result = agent.run_sync("Introduce yourself and recite your guardrails.")
    print(result.output)
'''


def render_pydantic_ai_bootstrap(persona_file: Path, collab_root: Path | None = None) -> str:
    """Render the ready-to-edit agent_setup.py for one persona.

    Text-only: does NOT import the pydantic-ai adapter, so emission works
    without the optional extra installed (running the script requires it).
    """
    root = collab_root if collab_root is not None else Path(".")
    return _PYDANTIC_AI_TEMPLATE.format(
        slug=persona_file.parent.name or persona_file.stem,
        persona_file=persona_file.as_posix(),
        collab_root=root.as_posix(),
    )
